# Конфигурация по умолчанию для системы прогнозирования спроса

# Общие настройки
general:
  log_level: INFO
  data_dir: data
  models_dir: data/models
  cache_dir: data/cache

# Настройки модели
model:
  type: random_forest  # linear, random_forest, exponential
  params:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 5
    min_samples_leaf: 2
    random_state: 42

# Настройки признаков
features:
  time_features: true
  lag_periods: [1, 7, 14, 30]
  rolling_windows: [7, 14, 30]
  target_col: quantity
  date_col: date

# Настройки обучения
training:
  test_size: 0.2
  validation_size: 0.1
  random_state: 42
  n_jobs: -1

# Настройки прогнозирования
forecasting:
  default_days_ahead: 30
  confidence_interval: 0.95
  min_forecast: 0
  max_forecast: null

# Настройки мониторинга
monitoring:
  metrics:
    - mae
    - rmse
    - mape
  alert_thresholds:
    mae: 10.0
    rmse: 15.0
    mape: 20.0
  check_interval: 3600  # в секундах

# Настройки безопасности
security:
  enable_auth: true
  enable_validation: true
  enable_logging: true
  log_file: logs/app/app.log
  error_log_file: logs/errors/error.log
  security_log_file: logs/security/security.log

# Настройки API
api:
  host: 0.0.0.0
  port: 8000
  debug: false
  workers: 4
  timeout: 60
  cors_origins:
    - http://localhost:3000
    - http://localhost:8080

# Настройки базы данных
database:
  type: postgresql  # postgresql, mysql, mongodb, redis
  host: localhost
  port: 5432
  name: demand_forecasting
  user: postgres
  password: postgres
  pool_size: 5
  max_overflow: 10
  pool_timeout: 30
  pool_recycle: 1800

# Настройки распределенных вычислений
distributed:
  enabled: false
  backend: dask  # dask, ray
  scheduler: local  # local, distributed
  workers: 4
  memory_limit: 4GB
  dashboard_address: :8787 